# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import meco_pb2 as meco__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in meco_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MecoServiceStub(object):
    """Define the gRPC service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_stream(
                '/meco.MecoService/Start',
                request_serializer=meco__pb2.ResourceDescriptor.SerializeToString,
                response_deserializer=meco__pb2.StartResponse.FromString,
                _registered_method=True)
        self.MecoCall = channel.unary_unary(
                '/meco.MecoService/MecoCall',
                request_serializer=meco__pb2.MecoRequest.SerializeToString,
                response_deserializer=meco__pb2.MecoResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_stream(
                '/meco.MecoService/Shutdown',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=meco__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class MecoServiceServicer(object):
    """Define the gRPC service
    """

    def Start(self, request, context):
        """Start processing and Emulation (Supporting either a filename or inline file content)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MecoCall(self, request, context):
        """Existing RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Shutdown an ongoing emulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MecoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_stream_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=meco__pb2.ResourceDescriptor.FromString,
                    response_serializer=meco__pb2.StartResponse.SerializeToString,
            ),
            'MecoCall': grpc.unary_unary_rpc_method_handler(
                    servicer.MecoCall,
                    request_deserializer=meco__pb2.MecoRequest.FromString,
                    response_serializer=meco__pb2.MecoResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_stream_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=meco__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meco.MecoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meco.MecoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MecoService(object):
    """Define the gRPC service
    """

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/meco.MecoService/Start',
            meco__pb2.ResourceDescriptor.SerializeToString,
            meco__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MecoCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meco.MecoService/MecoCall',
            meco__pb2.MecoRequest.SerializeToString,
            meco__pb2.MecoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/meco.MecoService/Shutdown',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            meco__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
