# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meco.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'meco.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmeco.proto\x12\x04meco\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n\x0bMecoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cMecoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\xa0\x01\n\x12ResourceDescriptor\x12\x1a\n\x10server_file_path\x18\x01 \x01(\tH\x00\x12\x1d\n\x13\x63lient_file_content\x18\x02 \x01(\tH\x00\x12\x14\n\x07save_as\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07\x64ry_run\x18\x04 \x01(\x08H\x02\x88\x01\x01\x42\x0b\n\tfile_dataB\n\n\x08_save_asB\n\n\x08_dry_run\"F\n\rStartResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0blog_message\x18\x03 \x01(\t\"I\n\x10ShutdownResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0blog_message\x18\x03 \x01(\t2\xb8\x01\n\x0bMecoService\x12\x38\n\x05Start\x12\x18.meco.ResourceDescriptor\x1a\x13.meco.StartResponse0\x01\x12\x31\n\x08MecoCall\x12\x11.meco.MecoRequest\x1a\x12.meco.MecoResponse\x12<\n\x08Shutdown\x12\x16.google.protobuf.Empty\x1a\x16.meco.ShutdownResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meco_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MECOREQUEST']._serialized_start=49
  _globals['_MECOREQUEST']._serialized_end=79
  _globals['_MECORESPONSE']._serialized_start=81
  _globals['_MECORESPONSE']._serialized_end=112
  _globals['_RESOURCEDESCRIPTOR']._serialized_start=115
  _globals['_RESOURCEDESCRIPTOR']._serialized_end=275
  _globals['_STARTRESPONSE']._serialized_start=277
  _globals['_STARTRESPONSE']._serialized_end=347
  _globals['_SHUTDOWNRESPONSE']._serialized_start=349
  _globals['_SHUTDOWNRESPONSE']._serialized_end=422
  _globals['_MECOSERVICE']._serialized_start=425
  _globals['_MECOSERVICE']._serialized_end=609
# @@protoc_insertion_point(module_scope)
