# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: meco.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'meco.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmeco.proto\x12\x04meco\"\x1e\n\x0bMecoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cMecoResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x92\x01\n\x12ResourceDescriptor\x12\x13\n\tfile_path\x18\x01 \x01(\tH\x00\x12\x16\n\x0c\x66ile_content\x18\x02 \x01(\tH\x00\x12\x14\n\x07save_as\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07\x64ry_run\x18\x04 \x01(\x08H\x02\x88\x01\x01\x42\x0b\n\tfile_dataB\n\n\x08_save_asB\n\n\x08_dry_run\"1\n\rStartResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2x\n\x0bMecoService\x12\x31\n\x08MecoCall\x12\x11.meco.MecoRequest\x1a\x12.meco.MecoResponse\x12\x36\n\x05Start\x12\x18.meco.ResourceDescriptor\x1a\x13.meco.StartResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'meco_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MECOREQUEST']._serialized_start=20
  _globals['_MECOREQUEST']._serialized_end=50
  _globals['_MECORESPONSE']._serialized_start=52
  _globals['_MECORESPONSE']._serialized_end=83
  _globals['_RESOURCEDESCRIPTOR']._serialized_start=86
  _globals['_RESOURCEDESCRIPTOR']._serialized_end=232
  _globals['_STARTRESPONSE']._serialized_start=234
  _globals['_STARTRESPONSE']._serialized_end=283
  _globals['_MECOSERVICE']._serialized_start=285
  _globals['_MECOSERVICE']._serialized_end=405
# @@protoc_insertion_point(module_scope)
