syntax = "proto3";

package meco;

// Define the gRPC service
service MecoService {
  // Existing RPC
  rpc MecoCall (MecoRequest) returns (MecoResponse);

  // Updated RPC: Start now supports both a filename and inline file content
  rpc Start (ResourceDescriptor) returns (StartResponse);
}

// Messages for MecoCall
message MecoRequest {
  string message = 1;
}

message MecoResponse {
  string message = 1;
}

// Message used by the Start RPC
message ResourceDescriptor {
  oneof file_data {
    string server_file_path = 1;    // File that already exists on the server
    string client_file_content = 2; // // File content sent from the client
  }
  optional string save_as = 3; // Save on the server and start the testbed
  optional bool dry_run = 4;   // Save file without starting the testbed
}

// Response from the Start RPC
message StartResponse {
  bool success = 1;
  string message = 2;
}
